### ISSUE TITLE
Don't strip trailing / from URLs

### ISSUE THREAD

**Issue by Khoulaiz** [ChargeIn/RestTester#15]
1. Enter URL with trailing '/'
2. Watch the log output. URL is without '/'

Expected: 
Do not change the URL that is requested by the user.

**Comment by ChargeIn** [comment]
Thank you for the bug report. Who would have guessed that the "split" function works differently in java than in other languages.

I fixed the issue and release a patch. The new version 1.4.1 should be available in a few days.
