### ISSUE TITLE
Add save option for current request

### ISSUE THREAD

**Issue by domgom** [ChargeIn/RestTester#20]
When a request is filled and sent there doesn't seem to be a way of saving it.
Only using the button "Add New Request" beforehand it allows for the request to get persisted.

Allowing to save a request without having to "Add New Request" and enter the data again would be a great usability improvement.

**Comment by ChargeIn** [comment]
Hey thank you for the valuable feedback.

Luckly I just merged this feature on monday :) . I will do some more reworking, but I expect this to be done by next week.

With the next release the content will stay the same when you press "new request" and had not select anything in the tree beforehand.
