### ISSUE TITLE
I have a working solution for adding checkboxes to request headers

### ISSUE THREAD

**Issue by shankuroy** [ChargeIn/RestTester#9]
I have a working solution for adding checkboxes to request headers.
Headers are included in the request only if they are enabled via checkbox and have non-empty keys. Empty values are allowed.
This allows for easier testing of various headers without having to delete and rewrite them each time.

<img width="1097" alt="resttester_header_checkbox" src="https://github.com/ChargeIn/RestTester/assets/64715768/18e4f733-45f7-4acb-8cda-15aeb34829d9">

How do I push my solution for a review? I was unable to push my branch for a review since I don't have the correct access rights. 

Next goal is to make this work for query params.

One issue I ran into is adjusting the size of the checkbox to match the size of the delete button. All values of `Dimension` resulted in the same default checkbox size.

**Comment by ChargeIn** [comment]
Hey, nice work 👍

The way github works, is that you need to fork the repository (it creates a copy to your own github page). There you can push you changes and create a pull request for the repo.

See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by shankuroy** [comment]
Makes sense, thanks. I've forked and raised a PR. 
Closing this issue.

**Comment by ChargeIn** [comment]
Hey, 

since you wanted to work on the query params next. It might make sense to rework the query params view first to match the headers view.

We can probably use the same component for both cases.
